<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="EC2AMAZ-6E9TAIA" failures="1" tests="11" name="Default test" time="198.328" errors="0" timestamp="2021-11-22T09:32:07 UTC">
  <testcase classname="ccpa.testcases.HomepageTestDPP" name="aem.gene.com" time="19.087"/>
  <testcase classname="ccpa.testcases.HomepageTestDPP" name="aem-legacy.gene.com" time="17.098"/>
  <testcase classname="ccpa.testcases.HomepageTestDPP" name="https://www.actemrainfo.com/" time="17.056"/>
  <testcase classname="ccpa.testcases.HomepageTestDPP" name="www.emicizumabinfo.com" time="19.122"/>
  <testcase classname="ccpa.testcases.HomepageTestDPP" name="www.genentech-medicines.com" time="17.249"/>
  <testcase classname="ccpa.testcases.HomepageTestDPP" name="www.hemlibra-hcp.com" time="14.125"/>
  <testcase classname="ccpa.testcases.HomepageTestDPP" name="www.her2treatment.com" time="19.735">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at ccpa.testcases.HomepageTestDPP.LaunchUrl(HomepageTestDPP.java:132)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- www.her2treatment.com -->
  <testcase classname="ccpa.testcases.HomepageTestDPP" name="www.mytactictrial.com" time="16.962"/>
  <testcase classname="ccpa.testcases.HomepageTestDPP" name="www.researchakt.com" time="16.798"/>
  <testcase classname="ccpa.testcases.HomepageTestDPP" name="www.vabysmo.com" time="17.155"/>
  <testcase classname="ccpa.testcases.HomepageTestDPP" name="www.vabysmo-hcp.com" time="17.114"/>
</testsuite> <!-- Default test -->
